In [1]:
import numpy as np

In [ ]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
v=v[:,None]
# this converts into a new column where [:] this selects the 
# whole array and the none is used as an indexing
print(v)


[[200]
 [300]
 [400]]


In [10]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print(p.shape)
print(q.shape)
print((p+q))

(3, 1)
(3,)
[[10 11 12]
 [20 21 22]
 [30 31 32]]


# NumPy Broadcasting Visualization

## Code

```python
import numpy as np

p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])

print(p + q)
```

---

## Step 1: Original Arrays

### `p` → Shape `(3,1)` (Column Vector)

```text
┌────┐
│  0 │
├────┤
│ 10 │
├────┤
│ 20 │
└────┘
```

### `q` → Shape `(3,)` (1D Array)

```text
┌────┬────┬────┐
│ 10 │ 11 │ 12 │
└────┴────┴────┘
```

---

## Step 2: Align Shapes

```text
p : (3,1)
q : (3,)  → treated as (1,3)
```

```text
      (3,1)
      (1,3)
```

Compare from the right:

```text
1 vs 3  → broadcast
3 vs 1  → broadcast
```

Both arrays expand!

---

## Step 3: Broadcasting

### Expand `p` Horizontally

```text
┌────┬────┬────┐
│  0 │  0 │  0 │
├────┼────┼────┤
│ 10 │ 10 │ 10 │
├────┼────┼────┤
│ 20 │ 20 │ 20 │
└────┴────┴────┘
```

### Expand `q` Vertically

```text
┌────┬────┬────┐
│ 10 │ 11 │ 12 │
├────┼────┼────┤
│ 10 │ 11 │ 12 │
├────┼────┼────┤
│ 10 │ 11 │ 12 │
└────┴────┴────┘
```

---

## Step 4: Element-wise Addition

```text
┌────┬────┬────┐      ┌────┬────┬────┐
│  0 │  0 │  0 │      │ 10 │ 11 │ 12 │
├────┼────┼────┤  +   ├────┼────┼────┤
│ 10 │ 10 │ 10 │      │ 10 │ 11 │ 12 │
├────┼────┼────┤      ├────┼────┼────┤
│ 20 │ 20 │ 20 │      │ 10 │ 11 │ 12 │
└────┴────┴────┘      └────┴────┴────┘
```

↓

```text
┌────┬────┬────┐
│ 10 │ 11 │ 12 │
├────┼────┼────┤
│ 20 │ 21 │ 22 │
├────┼────┼────┤
│ 30 │ 31 │ 32 │
└────┴────┴────┘
```

---

## Final Result

```python
array([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32]
])
```

---

# Memory Trick

```text
(3,1) + (1,3)
      ↓
    (3,3)
```

```text
Column Vector  +  Row Vector
        ↓
     Matrix
```

### Visual Formula

```text
      [10 11 12]

[0 ]
[10]     +
[20]

        ↓

[10 11 12]
[20 21 22]
[30 31 32]
```

---

# Broadcasting Cheat Sheet

```text
(3,1) + (1,3)  → (3,3) ✅
(5,1) + (1,4)  → (5,4) ✅
(2,3) + (3,)   → (2,3) ✅
(2,3) + (2,1)  → (2,3) ✅
(2,3) + (2,)   → Error ❌
```

### Golden Rule

```text
Compare dimensions from RIGHT → LEFT

Equal ?      ✅
One is 1 ?   ✅ Broadcast
Otherwise ?  ❌ Error
```

In [11]:
import numpy as np
arr = 2 * np.arange(0,2,0.5)
if arr <= 0.6:
    print("condition satisfies")
else:
    print("condition doesn't satisfy") 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# NumPy Array Conditions

```python
arr = np.array([0., 1., 2., 3.])

arr <= 0.6
```

Output:

```python
[ True False False False ]
```

---

## Why This Fails?

```python
if arr <= 0.6:
```

`if` expects **one boolean**:

```python
True
```

or

```python
False
```

But NumPy returns:

```python
[ True False False False ]
```

❌ Multiple booleans → Error

---

## `.any()`

Checks if **at least one** value is `True`.

```python
(arr <= 0.6).any()
```

```text
T OR F OR F OR F
```

✅ `True`

---

## `.all()`

Checks if **all** values are `True`.

```python
(arr <= 0.6).all()
```

```text
T AND F AND F AND F
```

❌ `False`

---

## Quick Memory Trick

```text
.any() → OR  → One True is enough ✅

.all() → AND → Everything must be True ✅
```

In [ ]:
#8 
import numpy as np
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
mask = np.array([1, 0, 1, 0], dtype=bool)
print(X[row[:, np.newaxis], mask])

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [ ]:
# 9
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr=np.hstack((arr, arr[:, [0]]))
# arr[:,[0]] select the semi colon select all the rows and the zero indexing select the first element of every arary
print(arr)

[[1 2 3 1]
 [4 5 6 4]
 [7 8 9 7]]


# NumPy `hstack()` vs `vstack()`

## Memory Trick

```text
hstack → Horizontal → Left ↔ Right

vstack → Vertical → Up ↕ Down
```

---

## Example

```python
A = [[1,2],
     [3,4]]

B = [[5,6],
     [7,8]]
```

### `hstack()`

```python
np.hstack((A, B))
```

```text
1 2 | 5 6
3 4 | 7 8
```

Result:

```text
[[1 2 5 6]
 [3 4 7 8]]
```

✅ More Columns (Wider)

---

### `vstack()`

```python
np.vstack((A, B))
```

```text
1 2
3 4
----
5 6
7 8
```

Result:

```text
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
```

✅ More Rows (Taller)

---

## Quick Recall

```text
hstack → Wide 📏

vstack → Tall 📐
```

# 11 NumPy `expand_dims()` & `squeeze()`

## `expand_dims()`

👉 Adds a new dimension of size `1` at the specified axis.

```python
arr.shape = (3,3)

np.expand_dims(arr, axis=0) → (1,3,3)
np.expand_dims(arr, axis=1) → (3,1,3)
np.expand_dims(arr, axis=2) → (3,3,1)
```

### Memory Trick

```text
expand_dims(axis=i)
       ↓
Insert a 1 at position i
```

---

## `squeeze()`

👉 Removes the dimension at the specified axis **only if its size is 1**.

```python
arr.shape = (3,3,1)

arr.squeeze(axis=2) → (3,3) ✅
arr.squeeze(axis=0) → Error ❌
```

### Memory Trick

```text
squeeze(axis=i)
      ↓
Remove axis i
ONLY if size = 1
```

---

## Quick Visual

```text
(3,3)

axis=1

(3,1,3)
```

```text
(3,3,1)

remove axis=2

(3,3)
```

In [4]:
# 12
arr=[[1,2],[3,4],[5,6]]

arr = np.array(arr)

result = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(result)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 5 6 0]
 [0 0 0 0]]


# NumPy `np.pad()` Cheat Sheet

## Syntax

```python
np.pad(array,
       pad_width,
       mode='constant',
       constant_values=0)
```

---

# `pad_width`

Controls how much padding is added.

### Same padding everywhere

```python
np.pad(arr, 1)
```

```text
1 layer on all sides
```

---

### Different padding per axis

```python
np.pad(arr, ((1,1), (2,2)))
```

```text
Rows    : (top, bottom)
Columns : (left, right)

1 top
1 bottom
2 left
2 right
```

---

### Asymmetric padding

```python
np.pad(arr, ((1,2), (3,4)))
```

```text
1 top
2 bottom
3 left
4 right
```

---

# `mode`

Controls what values are used for padding.

### Constant (Default)

```python
np.pad(arr, 1, mode='constant')
```

```text
0 0 0
0 1 0
0 0 0
```

---

### Edge

```python
np.pad(arr, 1, mode='edge')
```

Repeats boundary values.

```text
1 1 2 2
1 1 2 2
3 3 4 4
3 3 4 4
```

---

### Reflect

```python
np.pad(arr, 1, mode='reflect')
```

Mirrors values excluding edges.

---

### Symmetric

```python
np.pad(arr, 1, mode='symmetric')
```

Mirrors values including edges.

---

### Wrap

```python
np.pad(arr, 1, mode='wrap')
```

Wraps values from opposite side.

---

# `constant_values`

Used only with `mode='constant'`.

### Default

```python
np.pad(arr, 1)
```

```text
Pads with 0
```

---

### Custom Value

```python
np.pad(arr,
       1,
       mode='constant',
       constant_values=9)
```

```text
Pads with 9
```

---

# Memory Tricks

## 2D Arrays

```text
((top,bottom),
 (left,right))
```

---

## Most Common Interview Pattern

```python
np.pad(arr,
       1,
       mode='constant',
       constant_values=0)
```

```text
Add one layer of zeros around the matrix.
```

---

## Quick Recall

```text
pad_width       → How much padding?

mode            → What kind of padding?

constant_values → Which value to pad with?
```

In [5]:
# 13
import numpy as np
def seq(start, length, step):
    ''' start, length and step are in form of integers all representing the attributes as their names suggest
        output -> A numpy array is expected to be returned'''

    # YOUR CODE GOES HERE
    # sequence =[]
    # for i in range(length):
    #     sequence.append(start+(i*step))
    # sequence= np.array(sequence)   
    sequence=np.arange(start=start,stop=start+(length-1)*step,step=step) 

    
    
    
    return sequence
display(seq(5,10,3))

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [ ]:
# 14
import numpy as np
def rotate_img(mat):
    '''INPUT -> A 2d numpy array
       OUTPUT -> A 2d numpy array is expected to be returned'''

    # YOUR CODE GOES HERE
    return  np.rot90(mat,k=3)
    
    # return OUTPUT

# 🔄 NumPy `rot90()`

## Syntax

```python
np.rot90(arr, k=1)
```

- `k=1` → 90° Counterclockwise ↺
- `k=2` → 180°
- `k=3` → 270° Counterclockwise ↺
- `k=-1` → 90° Clockwise ↻

---

## Example

```text
Original

1 2 3
4 5 6
7 8 9
```

### `np.rot90(arr)`

```text
3 6 9
2 5 8
1 4 7
```

### `np.rot90(arr, 2)`

```text
9 8 7
6 5 4
3 2 1
```

### `np.rot90(arr, -1)`

```text
7 4 1
8 5 2
9 6 3
```

---

## 🧠 Memory Trick

```text
k = 1  → 90°  ↺

k = 2  → 180°

k = 3  → 270° ↺

k = -1 → 90°  ↻
```

```text
Positive k → Counterclockwise ↺
Negative k → Clockwise ↻
```

In [ ]:
# 15
import numpy as np
def specific_elements(mat1,mat2,r1,r2,c1,c2):
    '''mat1,mat2 are the two 2d numpy array.
       r1,r2 are the start and end of rows indices
       c1,c2 are the start and end of columns indices
       Output = Return a numpy array according to indices'''
    
    # STEP1 CHECK whether matrix multiplication is possible
    noofcolumns=mat1.shape[1]
    noofrows=mat2.shape[0]
    if(noofcolumns!=noofrows):
        return -1
    # the only time the matrix multipliaction doesnot occur is when the
    # number of columns of first matrix is not equal to second matrix rows
    
    
    ## STEP 2 Perform matrix multiplication
    
    matmul_array = np.matmul(mat1,mat2)
    
    ## STEP 3 slice the array based on range value
    
    result = matmul_array[r1:r2,c1:c2]
    
    return result

In [ ]:
# 16
import numpy as np


def extract_subarray(arr):
    '''
    INPUT: arr -> 2D array
    
    OUPUT: result -> 2D array
    '''
    
    ### STEP1: Get the rows (2nd  to 4th row)
    
    row_array = arr[1:4,:]
    
    
    #### STEP 2: Get the last 3 cols from the row array
    
    cols_array = row_array[:,-3:]
    
    #### STEP3: Reverse the rows in cols array
    
    result = cols_array[::-1]
    

    return result

# 🔄 Reverse in NumPy

## 1D Array

```python
arr[::-1]
```

### Example

```python
arr = np.array([1, 2, 3, 4, 5])

arr[::-1]
```

```text
[5 4 3 2 1]
```

---

## 2D Array

### Reverse Rows

```python
arr[::-1]
```

```text
Bottom → Top
```

---

### Reverse Columns

```python
arr[:, ::-1]
```

```text
Right → Left
```

---

### Reverse Entire Matrix

```python
arr[::-1, ::-1]
```

---

## How `[::-1]` Works

```python
[start : stop : step]
```

```python
[::-1]
```

means:

```text
Start = End
Stop  = Beginning
Step  = -1
```

---

## 🧠 Memory Trick

```text
[::-1]

-1 = Move Backwards
```

```text
Forward  → [::1]

Backward → [::-1]
```

In [ ]:
# 17
import numpy as np

def calculate_mean_age(birds, age):
    '''
    INPUT: birds, age -> 1D array
    
    OUPUT: mean_age -> float variable
    '''
    
    mean_age = None
    
    ## STEP1. Create mask to get Crane birds from birds array
    mask = birds=="Cranes"
    
    ## STEP2. Get the age of crane birds
    
    crane_ages =age[mask]
    
    ## STEP 3. Calculate mean age of crane birds
    
    mean_age = np.mean(crane_ages)
    
    ## STEP 4. Round off the mean age to 2 decimal points
    
    mean_age = np.round(mean_age,2)
    
    
    
    return mean_age

# 🎭 NumPy Masks

## What is a Mask?

A boolean array used to **filter, select, or modify** data.

```python
mask = arr > 25
```

```text
Array : [10 20 30 40 50]

Mask  : [ F  F  T  T  T ]
```

```text
True  → Keep ✅
False → Ignore ❌
```

---

## Create a Mask

```python
mask = arr > 25
```

```python
[False False True True True]
```

---

## Filter Values

```python
arr[mask]
```

```python
[30 40 50]
```

---

## Modify Values

```python
arr[mask] = 0
```

```python
[10 20 0 0 0]
```

---

## Multiple Conditions

### AND `&`

```python
arr[(arr > 10) & (arr < 40)]
```

### OR `|`

```python
arr[(arr < 10) | (arr > 40)]
```

### NOT `~`

```python
arr[~mask]
```

---

## Count Matches

```python
np.sum(mask)
```

```text
Counts True values
```

---

## Column Selection

```python
mask = [True, False, True, False]

X[:, mask]
```

```text
Select columns 0 and 2
```

---

## 🧠 Memory Trick

```text
Mask = Boolean Filter

True  → Keep ✅

False → Drop ❌
```

```python
arr[mask]
```

```text
Apply Filter → Get Matching Values
```

In [ ]:
import numpy as np

def sort_birds(birds, age):
    '''
    INPUT: birds, age -> 1D numpy array
    
    OUTPUT: result -> sorted bird 1D array
    '''
    
    ## STEP 1 : Get the sorted index of age.
    
    sorted_age_index = np.argsort(age)
    # here argsort returns the index of particular element for getting sorted
    
    ## STEP 2: Use the index from previous step to get sorted birds
    
    result = birds[sorted_age_index]
    
    return result

In [ ]:
# 19
import numpy as np
def oldest_bird(birds, age):
    ''' birds[i] consist of the names of the type of ith bird
        age[i] consist of the age of ith bird'''
        
    ## STEP 1: Get the index of maximum age element
    
    max_age_index =np.argmax(age)
    
    
    ## STEP 2: Get the bird with maxium age using the above index
    
    old_bird = birds[max_age_index]
    
    
    return old_bird

# 🎯 NumPy `arg` Functions

## Memory Trick

```text
arg = Position / Index 📍

Normal Function → Value

arg Function    → Index
```

---

## Examples

### Maximum

```python
np.max(arr)
```

```text
Returns Maximum Value
```

```python
np.argmax(arr)
```

```text
Returns Index of Maximum Value
```

---

### Minimum

```python
np.min(arr)
```

```text
Returns Minimum Value
```

```python
np.argmin(arr)
```

```text
Returns Index of Minimum Value
```

---

### Sorting

```python
np.sort(arr)
```

```text
Returns Sorted Values
```

```python
np.argsort(arr)
```

```text
Returns Indices that would sort the array
```

---

### Condition Match

```python
np.argwhere(arr > 10)
```

```text
Returns Indices where condition is True
```

---

## 🧠 Quick Recall

```text
max()      → Value

argmax()   → Index

min()      → Value

argmin()   → Index

sort()     → Values

argsort()  → Indices
```

```text
If it starts with "arg"
        ↓
Usually returns positions / indices 📍
```

In [ ]:
# 20
import numpy as np

def get_array_properties(arr):
    '''
    INPUT: arr -> A nD array
    
    OUTPUT: result -> tuple consisting of shape and dimension
    '''
    
    ## STEP 1. Get the shape of array
    
    shape = arr.shape
    
    ## STEP 2. Get the dimension of array
    
    dim = arr.ndim
    
    
    return shape,dim

In [ ]:
# 27
import numpy as np

def check_conditions(arr, k):
    '''
    INPUT: arr, k
    
    OUTPUT: result -> bool
    '''
    
    result = None
    
    ## STEP 1 : Create mask for the given condition
    
    mask = (arr%2==0) & (arr>k)
    
    ## STEP 2: Use logical function on mask
    
    result = np.all(mask)
    
    
    
    return result

# 🧠 NumPy Logical Operations — Interview Essentials

> Master these 6 concepts and you'll solve **90% of NumPy filtering questions**.

---

## 🎭 Masks (Boolean Filters)

```python
mask = arr > 10
```

```text
Array : [ 5 10 15 20 ]

Mask  : [ F  F  T  T ]
```

```text
True  ✅ Keep
False ❌ Ignore
```

---

## 🔍 Filtering Data

```python
arr[mask]
```

### Example

```python
arr[arr > 10]
```

```text
[15 20]
```

---

## ✅ `np.all()`

Checks if **EVERY element** satisfies a condition.

```python
np.all(arr > 0)
```

```text
True
```

### Memory

```text
ALL = AND
```

```text
[T T T T] → True

[T F T T] → False
```

---

## 🚀 `np.any()`

Checks if **AT LEAST ONE element** satisfies a condition.

```python
np.any(arr > 100)
```

### Memory

```text
ANY = OR
```

```text
[F F T F] → True

[F F F F] → False
```

---

## 🔗 AND (`&`)

Both conditions must be true.

```python
(arr > 10) & (arr < 20)
```

```text
10 < x < 20
```

⚠️ Always use parentheses.

---

## 🔀 OR (`|`)

At least one condition must be true.

```python
(arr < 10) | (arr > 20)
```

```text
x < 10 OR x > 20
```

---

## 🔄 NOT (`~`)

Reverse the mask.

```python
~mask
```

```text
Before : [T F T]

After  : [F T F]
```

---

## 🔢 Count Matching Values

```python
np.sum(mask)
```

```text
Counts True values
```

Example:

```python
np.sum(arr > 10)
```

```text
3
```

---

# 🎯 Ultimate Cheat Sheet

| Operation | Meaning |
|------------|----------|
| `arr[mask]` | Filter values |
| `np.all(mask)` | All True? |
| `np.any(mask)` | Any True? |
| `&` | AND |
| `\|` | OR |
| `~` | NOT |
| `np.sum(mask)` | Count True values |

---

# 🏆 Golden Rule

```text
Mask = Boolean Filter

True  → Keep ✅

False → Drop ❌
```

```python
mask = (arr > 10) & (arr < 20)

result = arr[mask]
```

```text
Create Mask
      ↓
Apply Mask
      ↓
Get Filtered Values
```

In [ ]:
# 29
import numpy as np

def split(arr, k):
    '''
    INPUT: arr, k
    
    OUTPUT: split_arr -> list of arrays
    '''
    
    split_arr = np.split(arr,k,axis=0)
    # here axis can also be explictedly present it can be 0 or 1
    # in case of 0 it is row and in case of 1 it is column

    
    ## CODE starts here
    
    
    
    return split_arr

# 31 ✂️ NumPy `split()` — Interview Trick

```python
arr = np.arange(10)
```

```text
[0 1 2 3 4 5 6 7 8 9]
```

---

## Integer Argument

```python
np.split(arr, n)
```

```text
Split into n EQUAL parts
```

⚠️ Array length must be divisible by `n`.

### Example

```python
np.split(arr, 5)
```

```text
10 ÷ 5 = 2 ✅
```

Works.

---

### Example

```python
np.split(arr, 3)
```

```text
10 ÷ 3 = 3.33 ❌
```

Raises:

```text
ValueError:
array split does not result in an equal division
```

---

## List Argument

```python
np.split(arr, [2, 5])
```

```text
Split at index 2
Split at index 5
```

```text
[0 1] | [2 3 4] | [5 6 7 8 9]
```

✅ Works

---

## Out-of-Range Index

```python
np.split(arr, [5, 12])
```

```text
[0 1 2 3 4]
[5 6 7 8 9]
[]
```

✅ Still Works

---

# 🧠 Golden Rule

```text
np.split(arr, n)
       ↓
Equal Parts Required ⚠️
```

```text
np.split(arr, [i, j])
       ↓
Split at Positions 📍
```

### Answer to the Question

```python
np.split(arr, 3)
```

❌ Raises Error because `10` cannot be divided equally into `3` parts.

In [ ]:
# 32
import numpy as np

def split(arr):
    '''
    INPUT: arr -> 2D array
    
    OUTPUT: subarrays -> list of 2D arrays
    '''
    
    subarrays = np.split(arr,[2,3],axis=1)
    ### CODE starts here 
    
    
    
    return subarrays

# 36 🎯 NumPy 3D Slicing

```python
arr[:, 0, :1]
```

## Shape Guide

```text
(2, 2, 2)

Axis 0 → Blocks 📦
Axis 1 → Rows 📄
Axis 2 → Columns 📊
```

---

## Slice Breakdown

```python
:     → All Blocks

0     → First Row

:1    → First Column
```

---

## Visualization

```text
Block 0          Block 1

[0 1]            [4 5]
[2 3]            [6 7]

   ↓                ↓

[0]              [4]
```

---

## Result

```python
array([
    [[0]],
    [[4]]
])
```

### Shape

```text
(2, 1, 1)
```

---

## 🧠 Memory Trick

```text
arr[:, 0, :1]

(All Blocks,
 First Row,
 First Column)
```

```text
:   → All

0   → First

:1  → First Column
```

# 37 🧠 NumPy Copy vs View

## ✅ Deep Copy (New Memory)

```python
arr.copy()

arr * 1

arr[arr > 0]      # Masking

arr[[0,2,4]]      # Fancy Indexing
```

```text
Original ↔ Independent Copy
```

Changes do **NOT** affect each other.

---

## ❌ View (Shared Memory)

```python
arr[:]

arr.reshape(...)

arr.T

arr.view()
```

```text
Original ↔ Same Data
```

Changes affect both arrays.

---

## 🎯 Golden Rule

```text
Masking         → Copy ✅

Fancy Indexing → Copy ✅

Slicing        → View ❌

Reshape        → View ❌
```

---

## 🚀 Interview Shortcut

```text
New Memory ? → Copy ✅

Same Memory ? → View ❌
```

# 39 🔄 NumPy Type Casting

## Change Data Type

```python
arr.astype('float64')
```

or

```python
arr.astype(float)
```

---

## Example

```python
arr = np.array([10, 20, 30])

arr = arr.astype(float)
```

Output:

```python
array([10., 20., 30.])
```

---

## Common Types

```python
astype(int)
astype(float)
astype(str)
astype(bool)
```

---

## 🧠 Memory Trick

```text
astype()
   ↓
Change Type
```

```python
arr.astype(float)
```

```text
int  → float

float → int

int  → str
```

# 46 🎯 NumPy Indexing

## ✅ Fancy Indexing

```python
arr[[0,2,4,6]]
```

Select specific indices.

---

## ✅ Slicing

```python
arr[::2]
```

Take every 2nd element.

---

## ❌ Invalid for 1D Arrays

```python
arr[0,2,4,6]
```

```text
Comma-separated indices imply multiple dimensions.
```

---

## 🧠 Memory Trick

```text
[0,2,4,6]   ❌

[[0,2,4,6]] ✅
```

```text
Single []  → One index

Double [[]] → Multiple indices
```