In [1]:
import numpy as np

Creating Array from List


In [2]:
# 1d array
one_d=np.array([1,2,3])
two_d=np.array([[1,2,3],[4,5,6]])
print(one_d)
print(two_d)



[1 2 3]
[[1 2 3]
 [4 5 6]]


Difference Between List and Numpy Array

In [ ]:
listmultiplication=[1,2,3]
nparraymultiplication=np.array([1,2,3])
print(listmultiplication*2)
print(nparraymultiplication*2)
# this is broadcasting nothing but expanding the scalar and performing the calculations

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [4]:
print(np.arange(10))
# this will gives from 0 to n-1
# and the parameters are start,stop and step

[0 1 2 3 4 5 6 7 8 9]


Creating Array from Scratch

In [5]:
zeros=np.zeros([3,4])
# this will generate the zeros 2d array of 3 rows and 4 columns
print(zeros)
ones=np.ones([3,4])
print(ones)
full=np.full([3,4],69)
# this is used to generate the matrix of specified value
print(full)
random=np.random.random((3,4))
print(random)
sequence=np.arange(0,10,3)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]]
[[0.77250296 0.49511558 0.33278248 0.40677242]
 [0.48507282 0.56089942 0.17392351 0.0172415 ]
 [0.08798489 0.97522805 0.8397503  0.65706702]]
[0 3 6 9]


### Vector Matrix and Tensor

In [6]:
vector=np.array([1,2,3])
matrix=np.array([[1,2,3],[4,5,6]])
tensor=np.array([[[1,2,3],[4,5,6]]])
# multi dimensional array is known as tensors
print(vector)
print(matrix)
print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]]


### Array Properties

In [7]:
array=np.array([[1,2,3],[4,5,6]])
print("shape",array.shape)
# gives rows and columns
print("dimension",array.ndim)
print("size",array.size)
print("dtype",array.dtype)

shape (2, 3)
dimension 2
size 6
dtype int64


### Array Reshaping


In [8]:
array1= np.arange(12)
reshaped=array1.reshape(3,4)
print("\n reshaped array",reshaped)
flatten=reshaped.flatten()
print("\n flatten array",flatten)
ravel=reshaped.ravel()
print("\n ravel array",ravel)
# ravel returns the orginal instead of copy
transposed=reshaped.T
print("\n Transposed array",transposed)



 reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flatten array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 ravel array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
