### Numpy Array Operations


In [ ]:
# Slicing
import numpy as np
arr=np.arange(10)
print("basic slicing",arr[2:4])
print("step slicing",arr[2:6:2])

basic slicing [2 3]
step slicing [2 4]


In [ ]:
two_d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element" ,two_d[1,1])
print("entire row", two_d[1])
print("entire column",two_d[:,1])

specific element 5
entire row [4 5 6]
entire column [2 5 8]


### Sorting Arrays

In [ ]:
unsorted=np.array([1,5,2,1,8,4,3])
print("sorted",np.sort(unsorted))
unsorted_2d=np.array([[1,3],[4,2],[3,5]])
print("row wise sorting",np.sort(unsorted_2d, axis=1))
print("column wise sorting",np.sort(unsorted_2d, axis=0))

sorted [1 1 2 3 4 5 8]
row wise sorting [[1 3]
 [2 4]
 [3 5]]
column wise sorting [[1 2]
 [3 3]
 [4 5]]


### Filtering Arrays

In [ ]:
array=np.arange(12)
print("even numbers",array[array%2==0])
# filtering with mask
mask=array%2==1
print("odd numbers",array[mask])

even numbers [ 0  2  4  6  8 10]
odd numbers [ 1  3  5  7  9 11]


### Fancy Indexing and Where Function

In [ ]:
array=np.array([1,3,4])
indexes=[0,1]
print(array[indexes])
resultindex=np.where(array>1)
print(np.where(array>1))
# this will return the indexes
print(array[resultindex])

[1 3]
(array([1, 2]),)
[3 4]


In [ ]:
numbers=np.arange(10)
conditioned_array=np.where(numbers>6 ,"true","false")
# first part is condition second part when the condition satisfies and third is whwn condition fails
print(conditioned_array)

['false' 'false' 'false' 'false' 'false' 'false' 'false' 'true' 'true'
 'true']


### Ading or Removing Data

In [ ]:
# concatination
array1=np.array([1,2,3])
array2=np.array([4,5,6])
print(np.concatenate((array1,array2)))

[1 2 3 4 5 6]


In [ ]:
# vstack vs hstack
import numpy as np
twod_array=np.array([[1,2],[3,4]])
newrow=np.array([5,6])
np.vstack((twod_array,newrow))
newcolumn=np.array([[7],[8]])
np.hstack((twod_array,newcolumn))
print(twod_array)
print(np.vstack((twod_array,newrow)))
print(np.hstack((twod_array,newcolumn)))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [ ]:
### Deletion

In [ ]:
array=np.array([1,2,3,4,5])
print(np.delete(array,2))

[1 2 4 5]
