In [1]:
import numpy as np


In [2]:
restaurantdata=np.array([
    [1,1000,2000,3000,4000],
    [2,100,200,300,400],
    [3,10,20,30,40],
    [4,1,2,3,4],
    [5,0,0,0,0]
])
print("shape",restaurantdata.shape)
# we should print the data of first 3 restaurants
print(restaurantdata[0:3])
# here slicing does not include the outer boundary
# we have to print all data without restaurant id
print(restaurantdata[:,1:])
print(restaurantdata[:3,1:])



shape (5, 5)
[[   1 1000 2000 3000 4000]
 [   2  100  200  300  400]
 [   3   10   20   30   40]]
[[1000 2000 3000 4000]
 [ 100  200  300  400]
 [  10   20   30   40]
 [   1    2    3    4]
 [   0    0    0    0]]
[[1000 2000 3000 4000]
 [ 100  200  300  400]
 [  10   20   30   40]]


In [3]:
# yearly total of restaurant
yearlysum=np.sum(restaurantdata[:,1:],axis=1)
totalturnover=np.sum(yearlysum)
minumsaleofeachrestaurant=np.min(restaurantdata[:,1:],axis=1)
maximumsalesperyear=np.max(restaurantdata[:,1:],axis=0)
averagesalesperrestaurant=np.average(restaurantdata[:,1:],axis=1)
cumsum=np.cumsum(restaurantdata[:,1:],axis=1)
print("yearly sum",yearlysum)
print("totalturnover",totalturnover)
print("minumsaleofeachrestaurant",minumsaleofeachrestaurant)
print("maximumsalesperyear",maximumsalesperyear)
print("averagesalesperrestaurant",averagesalesperrestaurant)
print("cumsum",cumsum)


yearly sum [10000  1000   100    10     0]
totalturnover 11110
minumsaleofeachrestaurant [1000  100   10    1    0]
maximumsalesperyear [1000 2000 3000 4000]
averagesalesperrestaurant [2500.   250.    25.     2.5    0. ]
cumsum [[ 1000  3000  6000 10000]
 [  100   300   600  1000]
 [   10    30    60   100]
 [    1     3     6    10]
 [    0     0     0     0]]


### Vectors

In [4]:
vector1=np.array([1,2])
vector2=np.array([3,4])
print("vextor addition",vector1+vector2)
print("vector multiplication",vector1*vector2)
print("dot product",np.dot(vector1,vector2))

vextor addition [4 6]
vector multiplication [3 8]
dot product 11


### Vectorisation

In [5]:
array=np.array(["hi","bye"])
# we need to captalise all the letters
# we can vectorise so that we can perform np like operations in case of scalars
vectorised_array=np.vectorize(str.upper)
print(vectorised_array(array))

['HI' 'BYE']
